## Task 1:
Writing a Python/NumPy code block that finds the distinct/unique common items between two arrays

In [116]:
#importing NumPy to Notebook
import numpy as np

#Creating 2 new arrays
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# creating a new array called result
result = (np.intersect1d(a, b)) #calling the np.intersect1d function to find common values in arrays a & b.
print("The common values between array a and array b are:") 
print(result) # printing new array with np.intersect1d function results

The common values between array a and array b are:
[2 4]


## Task 2:
Creating a new 5X3 array with numerical values of 1-15

In [120]:
# creating a new array called arr
#calling functions: 
# 1) np.arange function to generate 1D array of 15 elements 
# 2) np.reshape matrix function into a 3x5 2D array
arr = np.arange(1,16).reshape(3,5)
print("A 3x5 array looks as follows:")
print(arr) #print 3x5 array
print()
print("The transpose turnes the 3x5 array into a 5x3 array:")
print(arr.T) #applying the transpose method in order to swap the rows and columns of the array

A 3x5 array looks as follows:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

The transpose turnes the 3x5 array into a 5x3 array:
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


## Task 3
Writing a Python/Numpy code block that removes common items from two seperate arrays.

In [18]:
# creating 2 new arrays
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

result = np.setdiff1d(a,b) #calling the setdiff1d function that set difference between elements in a that are not in b
print("The new 1D array with values from array a that were distinct from array b are:")
print(result) # print the results of the new array that contains only the values from array a that didn't exsist in array b

The new 1D array with values from array a that were distinct from array b are:
[ 1  7  8 15]


## Task 4:
Creating a new array that containes the cumulative number of miles of biking from NYC to Key West on a period of 35 days, with 4 days of rest (31). In order to bike from NYC to Key West, one must bike a total number of 1,519 miles.

In [122]:
#create a new array to specify the 35 days of the biking journy
miles_per_day= np.arange(1,36) #calling the np.arange function to create a new array with 35 elements.
print("a new 1D array with 35 elements:")
print(miles_per_day) #print the new array

a new 1D array with 35 elements:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35]


In [125]:
#setting miles value for each day of biking
print("The daily bike distance between NYC to Key West in 31 days is:")
print(1519/31) #printing the value of the total distance dividing by the number of biking days
miles_per_day[0:36]=49 #setting each day of biking to 49
miles_per_day[10]=0 # setting days of rest, that eqaul 0 miles per day
miles_per_day[15]=0
miles_per_day[20]=0
miles_per_day[30]=0
print("The daily bike distance including days off is:")
print(miles_per_day) #printing the updated array that described the miles per day biked.

The daily bike distance between NYC to Key West in 31 days is:
49.0
The daily bike distance including days off is:
[49 49 49 49 49 49 49 49 49 49  0 49 49 49 49  0 49 49 49 49  0 49 49 49
 49 49 49 49 49 49  0 49 49 49 49]


In [126]:
# calculating the cumulative number of miles per day, creating a new array with the cumulative values
cum_miles = miles_per_day.cumsum(0) #calling the cumsum function to calculate the sum per day over the 35 days
print("The cumulative distance per day is:")
print(cum_miles) #printing the nre cumalitive array

The cumulative distance per day is:
[  49   98  147  196  245  294  343  392  441  490  490  539  588  637
  686  686  735  784  833  882  882  931  980 1029 1078 1127 1176 1225
 1274 1323 1323 1372 1421 1470 1519]


## Task 5:
Importing a data set containing the NYC Water consumption and preform various mathematical and statistical operations using NumPy’s slicing, methods, and functions.

In [57]:
#importing pandas package
import pandas

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').values

# verify you have an ndarray object
type(nyc_water)

numpy.ndarray

In [58]:
#printing original data set
print(nyc_water)

[[   1979.  7102100.     1512.      213. ]
 [   1980.  7071639.     1506.      213. ]
 [   1981.  7089241.     1309.      185. ]
 [   1982.  7109105.     1382.      194. ]
 [   1983.  7181224.     1424.      198. ]
 [   1984.  7234514.     1465.      203. ]
 [   1985.  7274054.     1326.      182. ]
 [   1986.  7319246.     1351.      185. ]
 [   1987.  7342476.     1447.      197. ]
 [   1988.  7353719.     1484.      202. ]
 [   1989.  7344175.     1402.      191. ]
 [   1990.  7335650.     1424.      194. ]
 [   1991.  7374501.     1469.      199. ]
 [   1992.  7428944.     1369.      184. ]
 [   1993.  7506166.     1368.5     182. ]
 [   1994.  7570458.     1357.7     179. ]
 [   1995.  7633040.     1325.7     174. ]
 [   1996.  7697812.     1297.9     169. ]
 [   1997.  7773443.     1205.5     155. ]
 [   1998.  7858259.     1219.5     155. ]
 [   1999.  7947660.     1237.2     156. ]
 [   2000.  8008278.     1240.4     155. ]
 [   2001.  8024963.5    1184.      148. ]
 [   2002. 

In [129]:
#creating new array that containes only the year values from the original set
year=nyc_water[:,0] # defining new array as axis 0 = all rows that have an axis 1 values of 0
print("Year array:")
print(year) #print new array

Year array:
[1979. 1980. 1981. 1982. 1983. 1984. 1985. 1986. 1987. 1988. 1989. 1990.
 1991. 1992. 1993. 1994. 1995. 1996. 1997. 1998. 1999. 2000. 2001. 2002.
 2003. 2004. 2005. 2006. 2007. 2008. 2009. 2010. 2011. 2012. 2013. 2014.
 2015. 2016. 2017.]


In [130]:
#creating new array that containes only the nyc population values from the original set
nyc_pop=nyc_water[:,1] # defining new array as axis 0 = all rows that have an axis 1 values of 1
print("Nyc Population array:")
print(nyc_pop) #print new array

Nyc Population array:
[7102100.  7071639.  7089241.  7109105.  7181224.  7234514.  7274054.
 7319246.  7342476.  7353719.  7344175.  7335650.  7374501.  7428944.
 7506166.  7570458.  7633040.  7697812.  7773443.  7858259.  7947660.
 8008278.  8024963.5 8041649.  8058334.5 8075020.  8091705.5 8108391.
 8125076.5 8141762.  8158447.5 8175133.  8284098.  8361179.  8422460.
 8471990.  8516502.  8537673.  8622698. ]


In [132]:
#creating new array that containes only the nyc water consumption values from the original set
nyc_consumption=nyc_water[:,2]# defining new array as axis 0 = all rows that have an axis 1 values of 2
print("NYC water consumption in million gallons per day:")
print(nyc_consumption) #print new array

NYC water consumption in million gallons per day:
[1512.  1506.  1309.  1382.  1424.  1465.  1326.  1351.  1447.  1484.
 1402.  1424.  1469.  1369.  1368.5 1357.7 1325.7 1297.9 1205.5 1219.5
 1237.2 1240.4 1184.  1135.6 1093.7 1099.5 1138.  1069.  1114.  1098.
 1007.5 1039.  1021.  1009.1 1006.1  996.  1009.  1002.   990.2]


In [133]:
#creating new array that containes only the nyc water consumption per calita values from the original set
capita_consumption=nyc_water[:,3]# defining new array as axis 0 = all rows that have an axis 1 values of 3
print("NYC water consumption per capita:")
print(capita_consumption) #print new aray

NYC water consumption per capita:
[213. 213. 185. 194. 198. 203. 182. 185. 197. 202. 191. 194. 199. 184.
 182. 179. 174. 169. 155. 155. 156. 155. 148. 141. 136. 136. 141. 132.
 137. 135. 123. 127. 123. 121. 119. 118. 118. 117. 115.]


Perperation work is complete- I now have 4 new seperate arrays that I can preform the calculations on more easily:

In [106]:
#finding the maximum yearly NYC consumption of water in millions of gallons per day
print("The yearly maximum water consumtion in NYC is:")
print (nyc_consumption.max()) #calling the max function on the nyc_consumption array and printing it

The yearly maximum water consumtion in NYC is:
1512.0


In [108]:
# Counting how many calendar years are represented within the data set
print("The data set represents the following number of calendar year:")
print(year.shape[0]) # calling the shape function to find the number of elements in the year array and printing it

The data set represents the following number of calendar year:
39


In [109]:
# Calculating the average NYC water consumption per capita
print("The average water consumption per capita in NYC is:")
print(capita_consumption.mean()) #calling the mean function to find the average value of the capita_consumption array and printing it

The average water consumption per capita in NYC is:
160.30769230769232


In [110]:
# Calculating the standard deviation of NYC water consumption per capita
print("The standard deviation of water consumption per capita is:")
print(capita_consumption.std()) #calling the std function to find the standard deviation of the capita_consumption array and printing it

The standard deviation of water consumption per capita is:
31.51894330370624


In [113]:
# Finding the values of increase or decrease of nyc population in the data set
print("The yearly changes in NYC population between 1979 -2017 are:")
pop_diff = np.diff(nyc_pop) #calling the diff function to find the numerical differences between the values in the nyc_pop array
print(pop_diff) # printing the new array pop_diff

The yearly changes in NYC population between 1979 -2017 are:
[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
