# Discussion Exercises

## Task 1
Your task is to replace each odd number with a value of -10 using only a single line of Python code. If done correctly your array should appear as follows:

In [2]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
#set a condition to the defined array, any number divided by 2 that has a remainder of 1 is an odd number, 
#change odd numbers to -10.  
arr[arr%2 == 1] = -10 
arr

array([[-10,   4, -10],
       [  0, -10,   2],
       [  6, -10,   8]])

## Task 2

Your task is to convert that 1-dimensional array to a 2-dimensional array containing 2 rows using only a single line of Python code.  If done correctly your array should appear as follows:

In [14]:
arr2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [94]:
# Using the NumPy reshape function: change 1-dimensional array to 2-dimensional array
arr3 = np.reshape(arr2, (2, 5)) #call function, define array and provide the number or rows (2) and number of columns (5)
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Task 3

Your task is to extract all items from that array that fall between 5 and 12 (inclusive) using only a single line of Python code .  If done correctly your array should appear as follows:

In [19]:
arr = np.array([3,1, 6, 17, 8, 42, 10, 39, 25, 12, 14,42])

In [105]:
# Set a condition to defined array, only assign values that are bigger or equal than 5 and smaller or equal to 12
arr4[(arr4 >= 5) & (arr4 <=12)]

array([ 6,  8, 10, 12])

## Task 4

Your task is to swap the first and second rows of that array using only a single line of Python code.  If done correctly your array should appear as follows:

In [86]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
#Swap rows in array by changing the position of the index numbers
arr[:, [0, 1]] = arr[:, [1, 0]]
arr

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])